# -*- coding: utf-8 -*-
"""Whisper_jfk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ISuvOgqxcdje1dz9C7R40mBNeQzrABjF
"""

### Audio to text using whisper

!pip install torch torchvision torchaudio

!pip install git+https://github.com/openai/whisper.git

import whisper

!git clone https://github.com/openai/whisper.git

import os
print(os.getcwd())

os.listdir()

os.getcwd()

import os
import whisper

model = whisper.load_model("tiny")

text = model.transcribe("jfk.flac")


print(text["text"])

jfk = text["text"]

with open("jfk_transcription.txt", "w") as file:
    file.write(jfk)

from google.colab import files
files.download("jfk_transcription.txt")

